name: Pull Request Report

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create Virtual Environment
        run: |
          python -m venv venv

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r github_pr_tool/requirements.txt

      - name: Run PR Tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          python github_pr_tool/github_pr_tool.py

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: pr-json-report
          path: |
            prs.json
            pr_details.json

      - name: Upload Excel Report
        uses: actions/upload-artifact@v4
        with:
            name: pr-excel-report
            path: |
              prs.xlsx
              pr_details.xlsx